uploads = []
outputs = []

[[generated]]
id = "9tqnOXf0F5K2N-6tHJmqA"
uri = "file://artifacts/storefront/public/images/category-phones.png"
type = "image"
title = "Futuristic phone dark background"

[[generated]]
id = "0KlumYtHz1KZHKqR4DLEk"
uri = "file://artifacts/storefront/public/images/category-laptops.png"
type = "image"
title = "Futuristic laptop dark background"

[[generated]]
id = "kN4lkeXhVLahw3Wzc6Ut6"
uri = "file://artifacts/storefront/public/images/category-headsets.png"
type = "image"
title = "Futuristic headset dark background"

[[generated]]
id = "Ox3oJFUv3pokhs3bNtT49"
uri = "file://artifacts/storefront/public/images/category-accessories.png"
type = "image"
title = "Tech accessories dark background"
