import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import bcrypt from "bcryptjs";
import * as schema from "../../lib/db/src/schema/index.js";

const { Pool } = pg;

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL must be set");
}

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool, { schema });

const PRESETS = [
  // ── Классика ──────────────────────────────────────────────────────────────
  {
    name: "Midnight Steel",
    description: "Брутальная нержавейка, тёмный циферблат",
    collectionName: null,
    watchfaceGeometry: "circle",
    watchfaceMaterial: "metal",
    watchfaceColor: "#0f172a",
    braceletMaterial: "metal_solid",
    braceletType: "solid",
    braceletColor: "#1e293b",
    handsEnabled: true,
    handsColor: "#cbd5e1",
    watchfaceText: null,
    watchfaceTextMode: "center",
    priceStars: 15,
    maxQuantity: 1000,
  },
  {
    name: "Arctic Frost",
    description: "Белоснежная керамика, полярная чистота",
    collectionName: null,
    watchfaceGeometry: "circle",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#f8fafc",
    braceletMaterial: "plastic_solid",
    braceletType: "solid",
    braceletColor: "#e2e8f0",
    handsEnabled: true,
    handsColor: "#0f172a",
    watchfaceText: null,
    watchfaceTextMode: "center",
    priceStars: 12,
    maxQuantity: 1000,
  },
  {
    name: "Crimson Core",
    description: "Алый акцент, стальной корпус",
    collectionName: null,
    watchfaceGeometry: "circle",
    watchfaceMaterial: "metal",
    watchfaceColor: "#7f1d1d",
    braceletMaterial: "leather",
    braceletType: "solid",
    braceletColor: "#1c1917",
    handsEnabled: true,
    handsColor: "#fbbf24",
    watchfaceText: null,
    watchfaceTextMode: "center",
    priceStars: 18,
    maxQuantity: 1000,
  },
  {
    name: "Carbon Ghost",
    description: "Угольный карбон, невидимость в темноте",
    collectionName: null,
    watchfaceGeometry: "square",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#0a0a0a",
    braceletMaterial: "resin",
    braceletType: "solid",
    braceletColor: "#171717",
    handsEnabled: false,
    handsColor: "#ffffff",
    watchfaceText: null,
    watchfaceTextMode: "center",
    priceStars: 20,
    maxQuantity: 1000,
  },
  {
    name: "Gold Rush",
    description: "Роскошное золото, классика вне времени",
    collectionName: null,
    watchfaceGeometry: "drawn",
    watchfaceMaterial: "metal",
    watchfaceColor: "#78350f",
    braceletMaterial: "metal_segmented",
    braceletType: "segmented",
    braceletColor: "#b8860b",
    handsEnabled: true,
    handsColor: "#fbbf24",
    watchfaceText: null,
    watchfaceTextMode: "center",
    priceStars: 25,
    maxQuantity: 1000,
  },
  {
    name: "Ocean Drive",
    description: "Морская синева, дух свободы",
    collectionName: null,
    watchfaceGeometry: "circle",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#1e3a5f",
    braceletMaterial: "cotton_fabric",
    braceletType: "solid",
    braceletColor: "#1e40af",
    handsEnabled: true,
    handsColor: "#60a5fa",
    watchfaceText: null,
    watchfaceTextMode: "center",
    priceStars: 14,
    maxQuantity: 1000,
  },

  // ── РОФЛ — абсурдный юмор, мем-культура ──────────────────────────────────
  {
    name: "ДОХУИЩА",
    description: "Ядрёная красота. Текст по кругу, буквы в хаосе.",
    collectionName: "РОФЛ",
    watchfaceGeometry: "circle",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#dc2626",
    braceletMaterial: "resin",
    braceletType: "solid",
    braceletColor: "#ef4444",
    handsEnabled: true,
    handsColor: "#ffffff",
    watchfaceText: "ДОХУИЩА",
    watchfaceTextMode: "circular",
    priceStars: 11,
    maxQuantity: 1000,
  },
  {
    name: "МНОГО",
    description: "Жёлтый крик. Слишком громко на любое запястье.",
    collectionName: "РОФЛ",
    watchfaceGeometry: "circle",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#ca8a04",
    braceletMaterial: "cotton_fabric",
    braceletType: "solid",
    braceletColor: "#facc15",
    handsEnabled: true,
    handsColor: "#1a1a1a",
    watchfaceText: "МНОГО",
    watchfaceTextMode: "circular",
    priceStars: 10,
    maxQuantity: 1000,
  },
  {
    name: "АЛЕ",
    description: "Зелёный шок. Кольцевые буквы. Алёёё??",
    collectionName: "РОФЛ",
    watchfaceGeometry: "square",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#15803d",
    braceletMaterial: "plastic_solid",
    braceletType: "solid",
    braceletColor: "#22c55e",
    handsEnabled: true,
    handsColor: "#f0fdf4",
    watchfaceText: "АЛЕ",
    watchfaceTextMode: "circular",
    priceStars: 9,
    maxQuantity: 1000,
  },
  {
    name: "TOO MUCH",
    description: "Фиолетовый хаос на запястье. Слишком.",
    collectionName: "РОФЛ",
    watchfaceGeometry: "drawn",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#6d28d9",
    braceletMaterial: "resin",
    braceletType: "solid",
    braceletColor: "#a855f7",
    handsEnabled: true,
    handsColor: "#fde68a",
    watchfaceText: "TOO MUCH",
    watchfaceTextMode: "circular",
    priceStars: 12,
    maxQuantity: 1000,
  },
  {
    name: "БЕЗ ПЯТИ ШЕСТЬ УТРОВ",
    description: "Оранжевый рассвет. Дедлайны горят синим пламенем.",
    collectionName: "РОФЛ",
    watchfaceGeometry: "circle",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#c2410c",
    braceletMaterial: "leather",
    braceletType: "solid",
    braceletColor: "#7c2d12",
    handsEnabled: false,
    handsColor: "#fed7aa",
    watchfaceText: "БЕЗ ПЯТИ ШЕСТЬ УТРОВ",
    watchfaceTextMode: "circular",
    priceStars: 13,
    maxQuantity: 1000,
  },
  {
    name: "ЧЕТЫРЕ ЧАСОВ ЧАСА",
    description: "Полночный кризис. Грамматика устала вместе с тобой.",
    collectionName: "РОФЛ",
    watchfaceGeometry: "square",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#1e1b4b",
    braceletMaterial: "resin",
    braceletType: "solid",
    braceletColor: "#312e81",
    handsEnabled: true,
    handsColor: "#a5b4fc",
    watchfaceText: "ЧЕТЫРЕ ЧАСОВ ЧАСА",
    watchfaceTextMode: "circular",
    priceStars: 11,
    maxQuantity: 1000,
  },
  {
    name: "A LOT",
    description: "Максимально международно. Просто A LOT.",
    collectionName: "РОФЛ",
    watchfaceGeometry: "circle",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#0f172a",
    braceletMaterial: "cotton_fabric",
    braceletType: "solid",
    braceletColor: "#1e293b",
    handsEnabled: true,
    handsColor: "#e2e8f0",
    watchfaceText: "A LOT",
    watchfaceTextMode: "circular",
    priceStars: 10,
    maxQuantity: 1000,
  },

  // ── ГИПЕРСЕРЬЕЗНОСТЬ — корпоративный ужас, бюрократический брутализм ───────
  {
    name: "KPI",
    description: "Часы для людей, чьи KPI не сходятся с дедлайном бытия.",
    collectionName: "ГИПЕРСЕРЬЕЗНОСТЬ",
    watchfaceGeometry: "square",
    watchfaceMaterial: "metal",
    watchfaceColor: "#09090b",
    braceletMaterial: "metal_solid",
    braceletType: "solid",
    braceletColor: "#18181b",
    handsEnabled: true,
    handsColor: "#e4e4e7",
    watchfaceText: "KPI",
    watchfaceTextMode: "center",
    priceStars: 20,
    maxQuantity: 1000,
  },
  {
    name: "DEADLINE",
    description: "Вместо делений — одно слово. Всё, что нужно знать.",
    collectionName: "ГИПЕРСЕРЬЕЗНОСТЬ",
    watchfaceGeometry: "square",
    watchfaceMaterial: "metal",
    watchfaceColor: "#1c1917",
    braceletMaterial: "metal_solid",
    braceletType: "solid",
    braceletColor: "#292524",
    handsEnabled: false,
    handsColor: "#d6d3d1",
    watchfaceText: "DEAD\nLINE",
    watchfaceTextMode: "center",
    priceStars: 19,
    maxQuantity: 1000,
  },
  {
    name: "Q1",
    description: "Серый стандарт. Квартал не ждёт. Никогда.",
    collectionName: "ГИПЕРСЕРЬЕЗНОСТЬ",
    watchfaceGeometry: "circle",
    watchfaceMaterial: "metal",
    watchfaceColor: "#27272a",
    braceletMaterial: "metal_segmented",
    braceletType: "segmented",
    braceletColor: "#3f3f46",
    handsEnabled: true,
    handsColor: "#a1a1aa",
    watchfaceText: "Q1",
    watchfaceTextMode: "center",
    priceStars: 18,
    maxQuantity: 1000,
  },
  {
    name: "ASAP",
    description: "Дресс-код тёмно-синий. Ответить нужно было вчера.",
    collectionName: "ГИПЕРСЕРЬЕЗНОСТЬ",
    watchfaceGeometry: "drawn",
    watchfaceMaterial: "metal",
    watchfaceColor: "#0f172a",
    braceletMaterial: "leather",
    braceletType: "solid",
    braceletColor: "#1e293b",
    handsEnabled: true,
    handsColor: "#f8fafc",
    watchfaceText: "ASAP",
    watchfaceTextMode: "center",
    priceStars: 22,
    maxQuantity: 1000,
  },
  {
    name: "EXEC",
    description: "Золотые стрелки на угольном. Молчаливое превосходство.",
    collectionName: "ГИПЕРСЕРЬЕЗНОСТЬ",
    watchfaceGeometry: "circle",
    watchfaceMaterial: "metal",
    watchfaceColor: "#111827",
    braceletMaterial: "metal_segmented",
    braceletType: "segmented",
    braceletColor: "#1f2937",
    handsEnabled: true,
    handsColor: "#f59e0b",
    watchfaceText: null,
    watchfaceTextMode: "center",
    priceStars: 25,
    maxQuantity: 1000,
  },

  // ── ЖИВНОСТЬ — 5 живых часов, существа на запястье ──────────────────────
  {
    name: "ПАУК",
    description: "Членистоногий. Восемь точек зрения на ваш запрос.",
    collectionName: "ЖИВНОСТЬ",
    watchfaceGeometry: "drawn",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#0a0a0a",
    braceletMaterial: "metal_segmented",
    braceletType: "segmented",
    braceletColor: "#1a1a1a",
    handsEnabled: true,
    handsColor: "#4ade80",
    watchfaceText: "EYE:spider",
    watchfaceTextMode: "center",
    priceStars: 22,
    maxQuantity: 1000,
  },
  {
    name: "КРАКЕН",
    description: "Из глубины. Присоски, щупальца, вертикальный зрачок.",
    collectionName: "ЖИВНОСТЬ",
    watchfaceGeometry: "circle",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#0c4a6e",
    braceletMaterial: "resin",
    braceletType: "solid",
    braceletColor: "#075985",
    handsEnabled: false,
    handsColor: "#7dd3fc",
    watchfaceText: "EYE:squid",
    watchfaceTextMode: "center",
    priceStars: 25,
    maxQuantity: 1000,
  },
  {
    name: "ДРАКОН",
    description: "Чешуя, когти, рептильный глаз не моргает просто так.",
    collectionName: "ЖИВНОСТЬ",
    watchfaceGeometry: "drawn",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#7f1d1d",
    braceletMaterial: "leather",
    braceletType: "solid",
    braceletColor: "#451a03",
    handsEnabled: true,
    handsColor: "#fde68a",
    watchfaceText: "EYE:reptile",
    watchfaceTextMode: "center",
    priceStars: 24,
    maxQuantity: 1000,
  },
  {
    name: "ЧУДИК",
    description: "Мохнатый паразит с выпученными глазами. Обнимает крепко.",
    collectionName: "ЖИВНОСТЬ",
    watchfaceGeometry: "circle",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#4a044e",
    braceletMaterial: "cotton_fabric",
    braceletType: "solid",
    braceletColor: "#7e22ce",
    handsEnabled: true,
    handsColor: "#f0abfc",
    watchfaceText: "EYE:gremlin",
    watchfaceTextMode: "center",
    priceStars: 20,
    maxQuantity: 1000,
  },
  {
    name: "КИБЕР",
    description: "Прозрачный полимер, пульсирующие вены, биомеханические зажимы.",
    collectionName: "ЖИВНОСТЬ",
    watchfaceGeometry: "square",
    watchfaceMaterial: "plastic",
    watchfaceColor: "#042f2e",
    braceletMaterial: "resin",
    braceletType: "solid",
    braceletColor: "#134e4a",
    handsEnabled: false,
    handsColor: "#5eead4",
    watchfaceText: "EYE:cyber",
    watchfaceTextMode: "center",
    priceStars: 28,
    maxQuantity: 1000,
  },
];

const ADMIN_USERS = [
  { username: "admin", password: "FutureAfterWatch3s", role: "admin" },
  { username: "courier1", password: "courier123", role: "courier" },
];

async function seed() {
  console.log("🌱 Seeding database...");

  console.log("  → Clearing existing presets...");
  await db.delete(schema.watchPresetsTable);

  console.log("  → Inserting presets...");
  for (const preset of PRESETS) {
    try {
      await db.insert(schema.watchPresetsTable).values(preset as any).onConflictDoNothing();
    } catch (err) {
      console.error(`    ✗ Failed to insert preset "${preset.name}":`, err);
    }
  }
  console.log(`  ✓ ${PRESETS.length} presets seeded`);

  console.log("  → Inserting admin users...");
  for (const user of ADMIN_USERS) {
    try {
      const passwordHash = await bcrypt.hash(user.password, 10);
      await db.insert(schema.adminUsersTable)
        .values({ username: user.username, passwordHash, role: user.role })
        .onConflictDoNothing();
    } catch (err) {
      console.error(`    ✗ Failed to insert user "${user.username}":`, err);
    }
  }
  console.log(`  ✓ ${ADMIN_USERS.length} admin users seeded`);

  console.log("✅ Seeding complete!");
  await pool.end();
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
